apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-v2
  namespace: pippo
spec:
  template:
    spec:
      replicas: 2
      containers:
      - name: nginx
        env:
        - name: test
          value: "true" 