apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - path: deployment.yaml


images:
- name: docker.io/nginx:1.17.3
  newName: registry.par-tec.it/nginx
  newTag: 1.17.3
