apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - path: deployment.yaml
    target:
      kind: Deployment

images:
- name: docker.io/nginx
  newName: registry.par-tec.it
  newTag: 1.17.3
