apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:1.17.3
          env:
          - name: MY_VAR
            value: "value" 
          ports:
            - containerPort: 80